Repository stamford-syntax-club/infra, pull requests merged in 2023-08, with the labels that each got.

#4 disable preallocatevolume & edit readme
  .gitignore
  stamfordcenter/README.md
  stamfordcenter/docker-compose.dev.yaml
  stamfordcenter/resources/B28CD300F40E27154FB0B3989A7C8672CBB2A08C.png
Labels: bug, documentation

#5 feat: prometheus alert for seaweedfs storage
  .gitignore
  stamfordcenter/README.md
  stamfordcenter/docker-compose.dev.yaml
  stamfordcenter/prometheus/alertmanager.yml
  stamfordcenter/prometheus/prometheus.yml
  stamfordcenter/prometheus/rules.yml
  stamfordcenter/resources/edit channel.png
  stamfordcenter/resources/get webhook.png
  stamfordcenter/resources/integration&view.png
  stamfordcenter/resources/services.png
Labels: documentation, enhancement

#8 Update README.md with port list
  stamfordcenter/README.md
Labels: documentation

#12 restructure folders & separate docker-compose file & bootstrap-teardown script
  README.md
  haproxy/docker-compose.dev.yaml
  haproxy/haproxy.cfg
  prometheus/README.md
  prometheus/assets/edit channel.png
  prometheus/assets/get webhook.png
  prometheus/assets/integration&view.png
  prometheus/conf/alertmanager.yml
  prometheus/conf/prometheus.yml
  prometheus/conf/rules.yml
  prometheus/docker-compose.dev.yaml
  s3/README.md
  s3/docker-compose.dev.yaml
  stamfordcenter/README.md
  stamfordcenter/docker-compose.dev.yaml
  stamfordcenter/resources/services.png
  start_dev.sh
  stop_dev.sh
Labels: documentation, enhancement, help wanted

#13 doc: operation playbook
  Operation.md
Labels: documentation

#22 🤖 change docker image version to 00b51804f1722385707bf87cec45ce94712e…
  stamfordcenter/docker-compose.dev.yaml
Labels: enhancement

#23 🤖 change docker image version to 68a487adcb05da2e27e694210ecf264c8c53…
  stamfordcenter/docker-compose.dev.yaml
Labels: enhancement
